mod 'inifile',   '1.0.0',  :github_tarball => 'puppetlabs/puppetlabs-inifile'
mod 'boxen',     '3.0.1',  :github_tarball => 'boxen/puppet-boxen'
mod 'git',       '1.2.5',  :github_tarball => 'boxen/puppet-git'
mod 'homebrew',  '1.4.1',  :github_tarball => 'boxen/puppet-homebrew'
