#!/bin/sh
# Make sure deps are available and run a Cardboard command.

set -e

cd $(dirname "$0")/..

SCRIPT=$(basename "$0")

if [ ! -d ".bundle/binstubs" ]; then
  bundle binstubs --path .bundle/binstubs librarian-puppet puppet puppet-lint
fi

bundle exec cardboard bootstrap
exec bundle exec cardboard "$SCRIPT" "$@"
